# Generated by Django 6.0.3 on 2026-04-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0003_rename_categoria_categorias_rename_tarea_tareas'),
        ('categorias', '0003_alter_categorias_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='categorias.categorias'),
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='prioridad',
        ),
        migrations.AlterField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Progreso', 'En progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=15),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
