# Generated by Django 6.0.3 on 2026-04-02 00:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categorias',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta (Rojo)'), ('M', 'Media (Amarillo)'), ('B', 'Baja (Verde)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='color',
            field=colorfield.fields.ColorField(default='#3498db', image_field=None, max_length=25, samples=None),
        ),
    ]
