# Generated by Django 6.0.3 on 2026-04-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_options_categorias_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='M', max_length=1),
        ),
    ]
